import { User, Proforma, AuditLog, Executive, Client } from './types';

export const MOCK_USERS: (User & { password: string })[] = [
  { id: '1', email: 'ejecutivo@starken.cl', password: 'Ejecutivo123', role: 'Ejecutivo', name: 'Ana Valenzuela', requires2FA: false },
  { id: '2', email: 'jefe@starken.cl', password: 'Jefatura123', role: 'Jefatura', name: 'Carlos Muñoz', requires2FA: false },
  { id: '3', email: 'admin@starken.cl', password: 'Admin123', role: 'Administrador', name: 'Luis Herrera', requires2FA: true },
  { id: '4', email: 'gerencia@starken.cl', password: 'Gerencia123', role: 'Gerencia', name: 'Patricia Ríos', requires2FA: true },
];

export const DEMO_2FA_CODE = '123456';

export const MOCK_EXECUTIVES: Executive[] = [
  {
    id: 'exe-1',
    nombre: 'Ana Valenzuela',
    email: 'ana.valenzuela@starken.cl',
    rut: '16.890.342-1',
    telefono: '+56 9 8452 1102',
    avatar: 'AV',
    clientesAsignadosCount: 14,
    proformasTotales: 38,
    proformasAprobadas: 32,
    proformasRechazadas: 4,
    tasaAprobacion: 84.2,
    tasaRechazo: 10.5,
    tiempoPromedioGeneracionDias: 1.4,
    tiempoPromedioAprobacionDias: 2.1,
    promedioVersiones: 1.2,
    cantidadReprocesos: 6,
    proformasPendientes: 2,
    proformasExpiradas: 1,
    proformasConvertidas: 31,
  },
  {
    id: 'exe-2',
    nombre: 'Rodrigo Sepúlveda',
    email: 'rodrigo.sepulveda@starken.cl',
    rut: '15.443.210-8',
    telefono: '+56 9 9120 4491',
    avatar: 'RS',
    clientesAsignadosCount: 18,
    proformasTotales: 46,
    proformasAprobadas: 37,
    proformasRechazadas: 6,
    tasaAprobacion: 80.4,
    tasaRechazo: 13.0,
    tiempoPromedioGeneracionDias: 1.8,
    tiempoPromedioAprobacionDias: 2.8,
    promedioVersiones: 1.4,
    cantidadReprocesos: 9,
    proformasPendientes: 3,
    proformasExpiradas: 2,
    proformasConvertidas: 35,
  },
  {
    id: 'exe-3',
    nombre: 'Marcela Soto',
    email: 'marcela.soto@starken.cl',
    rut: '17.210.984-5',
    telefono: '+56 9 7332 9011',
    avatar: 'MS',
    clientesAsignadosCount: 11,
    proformasTotales: 29,
    proformasAprobadas: 26,
    proformasRechazadas: 2,
    tasaAprobacion: 89.6,
    tasaRechazo: 6.9,
    tiempoPromedioGeneracionDias: 1.1,
    tiempoPromedioAprobacionDias: 1.6,
    promedioVersiones: 1.1,
    cantidadReprocesos: 3,
    proformasPendientes: 1,
    proformasExpiradas: 0,
    proformasConvertidas: 26,
  },
  {
    id: 'exe-4',
    nombre: 'Felipe Morales',
    email: 'felipe.morales@starken.cl',
    rut: '14.887.652-3',
    telefono: '+56 9 6554 2200',
    avatar: 'FM',
    clientesAsignadosCount: 15,
    proformasTotales: 34,
    proformasAprobadas: 24,
    proformasRechazadas: 8,
    tasaAprobacion: 70.6,
    tasaRechazo: 23.5,
    tiempoPromedioGeneracionDias: 2.3,
    tiempoPromedioAprobacionDias: 3.5,
    promedioVersiones: 1.7,
    cantidadReprocesos: 11,
    proformasPendientes: 2,
    proformasExpiradas: 3,
    proformasConvertidas: 21,
  },
  {
    id: 'exe-5',
    nombre: 'Camila Navarro',
    email: 'camila.navarro@starken.cl',
    rut: '18.112.450-9',
    telefono: '+56 9 5219 8834',
    avatar: 'CN',
    clientesAsignadosCount: 9,
    proformasTotales: 22,
    proformasAprobadas: 19,
    proformasRechazadas: 2,
    tasaAprobacion: 86.4,
    tasaRechazo: 9.1,
    tiempoPromedioGeneracionDias: 1.3,
    tiempoPromedioAprobacionDias: 1.9,
    promedioVersiones: 1.2,
    cantidadReprocesos: 3,
    proformasPendientes: 1,
    proformasExpiradas: 1,
    proformasConvertidas: 18,
  },
];

export const MOCK_PROFORMAS: Proforma[] = [
  {
    id: 'PF-2026-0204',
    cliente: 'Retail Logistics Chile S.A.',
    rut: '76.452.120-K',
    cuentaCorrienteId: 'CTA-001',
    cuentaCorrienteNombre: 'Cuenta Principal Retail (Banco de Chile)',
    ejecutivoId: 'exe-1',
    ejecutivoNombre: 'Ana Valenzuela',
    monto: 6540000,
    montoFormatted: '$6.540.000',
    estado: 'Pendiente de validación',
    versionActual: 'v2',
    estadoSupervision: 'Pendiente_Autorizacion',
    estadoComercial: 'Borrador',
    fecha: '25/08/2026 09:30',
    tipoAcuerdo: 'Tarifa diferenciada por SKU',
    conteoRechazos: 1,
    motivoRechazoPrincipal: 'Diferencia en recubitaje / medidas de SKUs',
    alertasElaboracion: ['3 ítems presentan recargo por zona extrema sin confirmación de orden de compra'],
    tiempoGeneracionDias: 1,
    tiempoAprobacionDias: 2,
    respaldoCorreo: 'correo_rechazo_retail_logistics.png',
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '24/08/2026 10:15',
        fechaRechazo: '25/08/2026 09:00',
        usuarioResponsable: 'Ana Valenzuela',
        motivo: 'Diferencia en recubitaje / medidas de SKUs volumétricos',
        observaciones: 'El cliente indica que 14 bultos fueron clasificados como Sobredimensión cuando correspondía Tarifa Estándar.',
        cambiosRealizados: ['Emisión inicial basada en órdenes de despacho del periodo 01-15 Agosto.'],
        monto: 6800000,
        respaldoCorreoUrl: '/demo_email_rechazado.png',
        items: [
          { id: 'it-1', codigo: 'SRV-STK-01', descripcion: 'Flete Express RM a Regiones', cantidad: 450, tarifaBase: 8500, descuentoPct: 10, total: 3442500 },
          { id: 'it-2', codigo: 'SRV-VOL-02', descripcion: 'Recargo Volumétrico Sobredimensión', cantidad: 120, tarifaBase: 15000, descuentoPct: 5, total: 1710000 },
          { id: 'it-3', codigo: 'SRV-EXT-03', descripcion: 'Despacho Zona Extrema (Aysén / Magallanes)', cantidad: 65, tarifaBase: 28000, descuentoPct: 10, total: 1638000 },
        ],
      },
      {
        version: 'v2',
        numeroVersion: 2,
        fechaCreacion: '25/08/2026 09:30',
        usuarioResponsable: 'Ana Valenzuela',
        motivo: 'Recálculo con factor volumétrico estándar y corrección de sobredimensión',
        observaciones: 'Se re-clasificaron los 14 bultos a Tarifa Estándar según contrato comercial.',
        cambiosRealizados: [
          'Corrección de 14 bultos de Sobredimensión a Tarifa Estándar (-$260.000)',
          'Validación de órdenes de despacho con cliente',
        ],
        monto: 6540000,
        estadoSupervision: 'Pendiente_Autorizacion',
        items: [
          { id: 'it-1', codigo: 'SRV-STK-01', descripcion: 'Flete Express RM a Regiones', cantidad: 450, tarifaBase: 8500, descuentoPct: 10, total: 3442500 },
          { id: 'it-2', codigo: 'SRV-VOL-02', descripcion: 'Recargo Volumétrico Sobredimensión', cantidad: 106, tarifaBase: 15000, descuentoPct: 5, total: 1510500, ajustadoEnV2: true },
          { id: 'it-3', codigo: 'SRV-EXT-03', descripcion: 'Despacho Zona Extrema (Aysén / Magallanes)', cantidad: 65, tarifaBase: 27000, descuentoPct: 10, total: 1587000, ajustadoEnV2: true },
        ],
      },
    ],
  },
  {
    id: 'PF-2025-0141',
    cliente: 'Distribuidora Sur S.A.',
    rut: '96.543.210-9',
    cuentaCorrienteId: 'CTA-8801',
    cuentaCorrienteNombre: 'Cta Corriente Comercial Sur (Banco Santander)',
    ejecutivoId: 'exe-3',
    ejecutivoNombre: 'Marcela Soto',
    monto: 7120000,
    montoFormatted: '$7.120.000',
    estado: 'Pendiente de validación',
    versionActual: 'v2',
    estadoSupervision: 'Pendiente_Autorizacion',
    estadoComercial: 'Borrador',
    fecha: '20/07/2025 16:45',
    tipoAcuerdo: 'Acuerdo marco corporativo',
    conteoRechazos: 1,
    motivoRechazoPrincipal: 'Inconsistencia en Tarifas / Descuentos negociados',
    alertasElaboracion: [
      'Versión 2 recalculada: Descuento comercial incrementado de 8% a 12% según anexo comercial.',
      'Requiere V°B° de Jefatura de Facturación Especial antes de ser enviada al cliente.',
    ],
    tiempoGeneracionDias: 2,
    tiempoAprobacionDias: 1,
    respaldoCorreo: 'correo_rechazo_distribuidora_sur.png',
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '20/07/2025 16:45',
        fechaRechazo: '21/07/2025 10:20',
        usuarioResponsable: 'Marcela Soto',
        motivo: 'Inconsistencia en Tarifas / Descuentos negociados',
        observaciones: 'El cliente reclamó que el anexo de descuento corporativo del 12% no fue aplicado en la línea de Distribución Paletizada.',
        cambiosRealizados: ['Versión original con tarifa base del 8% de descuento general.'],
        monto: 7400000,
        respaldoCorreoUrl: '/demo_email_rechazado.png',
        items: [
          { id: 'it-10', codigo: 'SRV-PAL-01', descripcion: 'Distribución Carga Paletizada Zona Central', cantidad: 80, tarifaBase: 50000, descuentoPct: 8, total: 3680000 },
          { id: 'it-11', codigo: 'SRV-PAQ-02', descripcion: 'Paquetería Consolidada B2B', cantidad: 320, tarifaBase: 12500, descuentoPct: 7, total: 3720000 },
        ],
      },
      {
        version: 'v2',
        numeroVersion: 2,
        fechaCreacion: '21/07/2025 11:00',
        usuarioResponsable: 'Marcela Soto',
        motivo: 'Ajuste de tarifario según anexo comercial y revalidación de cubicaje',
        observaciones: 'Se aplicó 12% en pallets y 10% en paquetería B2B según contrato 2025-C2. Reducción neta de $280.000.',
        cambiosRealizados: [
          'Ajuste de descuento de Pallets de 8% -> 12% (-$160.000)',
          'Ajuste de descuento en Paquetería B2B de 7% -> 10% (-$120.000)',
        ],
        monto: 7120000,
        estadoSupervision: 'Pendiente_Autorizacion',
        items: [
          { id: 'it-10', codigo: 'SRV-PAL-01', descripcion: 'Distribución Carga Paletizada Zona Central', cantidad: 80, tarifaBase: 50000, descuentoPct: 12, total: 3520000, ajustadoEnV2: true },
          { id: 'it-11', codigo: 'SRV-PAQ-02', descripcion: 'Paquetería Consolidada B2B', cantidad: 320, tarifaBase: 12500, descuentoPct: 10, total: 3600000, ajustadoEnV2: true },
        ],
      },
    ],
  },
  {
    id: 'PF-2025-0140',
    cliente: 'MegaStore Chile S.A.C.',
    rut: '78.456.789-1',
    cuentaCorrienteId: 'CTA-3011',
    cuentaCorrienteNombre: 'Cta Corriente MegaStore (Banco BCI)',
    ejecutivoId: 'exe-4',
    ejecutivoNombre: 'Felipe Morales',
    monto: 1980000,
    montoFormatted: '$1.980.000',
    estado: 'Derivada a KAM',
    versionActual: 'v3',
    estadoSupervision: 'No_Requiere',
    estadoComercial: 'Derivada_KAM',
    fecha: '20/07/2025 14:10',
    tipoAcuerdo: 'Tarifa especial regional',
    conteoRechazos: 3,
    motivoRechazoPrincipal: 'Discrepancia comercial no resuelta en V3',
    alertasElaboracion: ['Cliente acumula 3 rechazos consecutivos. Requiere intervención de Gerencia KAM.'],
    tiempoGeneracionDias: 3,
    tiempoAprobacionDias: 5,
    respaldoCorreo: 'correo_tercer_rechazo_megastore.png',
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '18/07/2025 10:00',
        fechaRechazo: '19/07/2025 11:30',
        usuarioResponsable: 'Felipe Morales',
        motivo: 'Diferencia en recubitaje / medidas de SKUs',
        observaciones: 'El cliente indicó que se aplicaron medidas teóricas mayores a las reales.',
        monto: 2200000,
        items: [
          { id: 'ms-1', codigo: 'SRV-STK-01', descripcion: 'Flete Express RM a Regiones', cantidad: 200, tarifaBase: 7000, descuentoPct: 5, total: 1330000 },
          { id: 'ms-2', codigo: 'SRV-VOL-02', descripcion: 'Recargo Volumétrico Retail', cantidad: 60, tarifaBase: 15000, descuentoPct: 3, total: 870000 },
        ],
      },
      {
        version: 'v2',
        numeroVersion: 2,
        fechaCreacion: '19/07/2025 15:40',
        fechaRechazo: '20/07/2025 11:00',
        usuarioResponsable: 'Felipe Morales',
        motivo: 'Error en la selección de Cuentas Corrientes',
        observaciones: 'Reajuste intermedio tras observaciones del cliente sobre recargo volumétrico.',
        monto: 2100000,
        items: [
          { id: 'ms-1', codigo: 'SRV-STK-01', descripcion: 'Flete Express RM a Regiones', cantidad: 200, tarifaBase: 7000, descuentoPct: 7, total: 1302000, ajustadoEnV2: true },
          { id: 'ms-2', codigo: 'SRV-VOL-02', descripcion: 'Recargo Volumétrico Retail', cantidad: 60, tarifaBase: 14000, descuentoPct: 5, total: 798000, ajustadoEnV2: true },
        ],
      },
      {
        version: 'v3',
        numeroVersion: 3,
        fechaCreacion: '20/07/2025 14:10',
        fechaRechazo: '20/07/2025 18:30',
        usuarioResponsable: 'Felipe Morales',
        motivo: 'Discrepancia comercial no resuelta en V3',
        observaciones: 'Ajuste final derivado a KAM para negociación de acuerdo tarifario.',
        monto: 1980000,
        items: [
          { id: 'ms-1', codigo: 'SRV-STK-01', descripcion: 'Flete Express RM a Regiones', cantidad: 200, tarifaBase: 6800, descuentoPct: 10, total: 1224000, ajustadoEnV2: true },
          { id: 'ms-2', codigo: 'SRV-VOL-02', descripcion: 'Recargo Volumétrico Retail', cantidad: 60, tarifaBase: 13000, descuentoPct: 3, total: 756000, ajustadoEnV2: true },
        ],
      },
    ],
  },
  {
    id: 'PF-2025-0143',
    cliente: 'Logística Pacífico S.A.',
    rut: '76.123.456-7',
    cuentaCorrienteId: 'CTA-9021',
    cuentaCorrienteNombre: 'Cta Pacif-Trans (Banco Itaú)',
    ejecutivoId: 'exe-3',
    ejecutivoNombre: 'Marcela Soto',
    monto: 4850000,
    montoFormatted: '$4.850.000',
    estado: 'Aprobada por Cliente',
    versionActual: 'v1',
    estadoSupervision: 'No_Requiere',
    estadoComercial: 'Aprobada_Cliente',
    fecha: '21/07/2025 09:30',
    tipoAcuerdo: 'Tarifa diferenciada',
    conteoRechazos: 0,
    tiempoGeneracionDias: 1,
    tiempoAprobacionDias: 1,
    respaldoCorreo: 'correo_aprobacion_logistica_pacifico.png',
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '21/07/2025 09:30',
        fechaAprobacion: '21/07/2025 14:15',
        usuarioResponsable: 'Marcela Soto',
        monto: 4850000,
        respaldoCorreoUrl: '/demo_email_aprobado.png',
      },
    ],
  },
  {
    id: 'PF-2025-0142',
    cliente: 'Trans-Andes Cargo Ltda.',
    rut: '77.890.123-4',
    cuentaCorrienteId: 'CTA-4410',
    cuentaCorrienteNombre: 'Cta Andina Fletes (Banco Scotiabank)',
    ejecutivoId: 'exe-2',
    ejecutivoNombre: 'Rodrigo Sepúlveda',
    monto: 2310000,
    montoFormatted: '$2.310.000',
    estado: 'Pendiente',
    versionActual: 'v1',
    estadoSupervision: 'No_Requiere',
    estadoComercial: 'Enviada_Cliente',
    fecha: '21/07/2025 11:15',
    tipoAcuerdo: 'Descuento volumétrico',
    conteoRechazos: 0,
    tiempoGeneracionDias: 1,
    tiempoAprobacionDias: 0,
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '21/07/2025 11:15',
        usuarioResponsable: 'Rodrigo Sepúlveda',
        monto: 2310000,
      },
    ],
  },
  {
    id: 'PF-2025-0139',
    cliente: 'Importadora Bello Ltda.',
    rut: '79.111.222-3',
    cuentaCorrienteId: 'CTA-1002',
    cuentaCorrienteNombre: 'Cta Bello Operaciones (Banco Estado)',
    ejecutivoId: 'exe-4',
    ejecutivoNombre: 'Felipe Morales',
    monto: 3440000,
    montoFormatted: '$3.440.000',
    estado: 'Pendiente',
    versionActual: 'v1',
    estadoSupervision: 'No_Requiere',
    estadoComercial: 'Enviada_Cliente',
    fecha: '19/07/2025 17:05',
    tipoAcuerdo: 'Tarifa diferenciada',
    conteoRechazos: 0,
    tiempoGeneracionDias: 2,
    tiempoAprobacionDias: 0,
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '19/07/2025 17:05',
        usuarioResponsable: 'Felipe Morales',
        monto: 3440000,
      },
    ],
  },
  {
    id: 'PF-2025-0138',
    cliente: 'Cencosud Retail S.A.',
    rut: '81.201.000-K',
    cuentaCorrienteId: 'CTA-8012',
    cuentaCorrienteNombre: 'Cta Jumbo / Santa Isabel Central (Banco de Chile)',
    ejecutivoId: 'exe-2',
    ejecutivoNombre: 'Rodrigo Sepúlveda',
    monto: 12450000,
    montoFormatted: '$12.450.000',
    estado: 'Facturado',
    versionActual: 'v1',
    estadoSupervision: 'No_Requiere',
    estadoComercial: 'Facturado',
    fecha: '18/07/2025 11:20',
    tipoAcuerdo: 'Acuerdo marco corporativo',
    conteoRechazos: 0,
    numeroFactura: 'FAC-890214',
    fechaFacturacion: '19/07/2025',
    archivoFacturaNombre: 'Factura_FAC-890214_Cencosud.pdf',
    respaldoCorreo: 'correo_aprobacion_cencosud.png',
    tiempoGeneracionDias: 1,
    tiempoAprobacionDias: 1,
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '18/07/2025 11:20',
        fechaAprobacion: '18/07/2025 16:30',
        usuarioResponsable: 'Rodrigo Sepúlveda',
        monto: 12450000,
        respaldoCorreoUrl: '/demo_email_aprobado.png',
      },
    ],
  },
  {
    id: 'PF-2026-0208',
    cliente: 'Falabella Retail S.A.',
    rut: '77.123.456-8',
    cuentaCorrienteId: 'CTA-5541',
    cuentaCorrienteNombre: 'Cta Proveedores Falabella (Banco Falabella)',
    ejecutivoId: 'exe-1',
    ejecutivoNombre: 'Ana Valenzuela',
    monto: 9800000,
    montoFormatted: '$9.800.000',
    estado: 'Pendiente de validación',
    versionActual: 'v2',
    estadoSupervision: 'Pendiente_Autorizacion',
    estadoComercial: 'Borrador',
    fecha: '25/08/2026 09:10',
    tipoAcuerdo: 'Tarifa preferencial eCommerce',
    conteoRechazos: 1,
    motivoRechazoPrincipal: 'Diferencia en recubitaje / medidas de SKUs',
    alertasElaboracion: [
      'Versión 2: Se recalcularon 18 envíos con peso volumétrico disputado.',
      'Requiere V°B° de Jefatura previo a notificación formal al cliente.',
    ],
    tiempoGeneracionDias: 1,
    tiempoAprobacionDias: 1,
    respaldoCorreo: 'correo_rechazo_falabella_v1.png',
    historialVersiones: [
      {
        version: 'v1',
        numeroVersion: 1,
        fechaCreacion: '24/08/2026 14:00',
        fechaRechazo: '25/08/2026 08:30',
        usuarioResponsable: 'Ana Valenzuela',
        motivo: 'Diferencia en recubitaje / medidas de SKUs',
        observaciones: 'El cliente objetó el factor de conversión 1:200 aplicado a paquetería express.',
        cambiosRealizados: ['Emisión de proforma con tarificación de bultos pesados.'],
        monto: 10450000,
        respaldoCorreoUrl: '/demo_email_rechazado.png',
        items: [
          { id: 'it-21', codigo: 'SRV-ECOM-01', descripcion: 'Despacho eCommerce Next Day RM', cantidad: 1200, tarifaBase: 4500, descuentoPct: 15, total: 4590000 },
          { id: 'it-22', codigo: 'SRV-ECOM-02', descripcion: 'Despacho eCommerce Regiones V/VIII', cantidad: 850, tarifaBase: 7800, descuentoPct: 10, total: 5967000 },
        ],
      },
      {
        version: 'v2',
        numeroVersion: 2,
        fechaCreacion: '25/08/2026 09:10',
        usuarioResponsable: 'Ana Valenzuela',
        motivo: 'Corrección de cubicaje y aplicación de factor 1:180 negociado',
        observaciones: 'Se ajustó el cubicaje con validación del centro de distribución San Bernardo. Monto total recalculado a $9.800.000 (-$650.000).',
        cambiosRealizados: [
          'Ajuste de tarifa en Regiones V/VIII con factor volumétrico estándar (-$650.000)',
        ],
        monto: 9800000,
        estadoSupervision: 'Pendiente_Autorizacion',
        items: [
          { id: 'it-21', codigo: 'SRV-ECOM-01', descripcion: 'Despacho eCommerce Next Day RM', cantidad: 1200, tarifaBase: 4500, descuentoPct: 15, total: 4590000 },
          { id: 'it-22', codigo: 'SRV-ECOM-02', descripcion: 'Despacho eCommerce Regiones V/VIII', cantidad: 850, tarifaBase: 7000, descuentoPct: 12, total: 5210000, ajustadoEnV2: true },
        ],
      },
    ],
  },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    rut: '76.452.120-K',
    razonSocial: 'Retail Logistics Chile S.A.',
    nombreFantasia: 'Retail Logistics',
    giro: 'Servicios Logísticos y Almacenaje Retail',
    contactoPrincipal: {
      nombre: 'Gonzalo Silva Valdés',
      email: 'gsilva@retaillogistics.cl',
      telefono: '+56 9 9876 5432',
      cargo: 'Jefe de Finanzas & Cobranzas',
    },
    cuentaCorriente: {
      id: 'CTA-001',
      numero: '00-128-49921',
      banco: 'Banco de Chile',
      lineaCredito: 50000000,
      saldoDisponible: 38200000,
      alias: 'Cuenta Principal Retail',
    },
    cuentasCorrientes: [
      { id: 'CTA-001', numero: '00-128-49921', banco: 'Banco de Chile', lineaCredito: 50000000, saldoDisponible: 38200000, alias: 'Cuenta Principal Retail' },
      { id: 'CTA-002', numero: '55-128-49922', banco: 'Banco Santander', lineaCredito: 40000000, saldoDisponible: 32500000, alias: 'Cuenta Operativa Express' },
      { id: 'CTA-003', numero: '22-128-49923', banco: 'Banco BCI', lineaCredito: 25000000, saldoDisponible: 20100000, alias: 'Cuenta Regiones Sur' },
    ],
    ejecutivoId: 'exe-1',
    ejecutivoNombre: 'Ana Valenzuela',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-1',
      tipo: 'Tarifa diferenciada por SKU',
      descuentoAcordado: '10% base + 5% sobre 500 bultos/mes',
      plazoPagoDias: 30,
      validezHasta: '31/12/2026',
      observaciones: 'Requiere detalle anexo por centro de costo en proforma.',
    },
    proformasIds: ['PF-2026-0204'],
    historialModificaciones: [
      {
        id: 'hm-1',
        fecha: '15/01/2026 11:30',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Asignación Ejecutivo',
        detalle: 'Reasignación de Rodrigo Sepúlveda a Ana Valenzuela para optimización de cartera.',
        valorAnterior: 'Rodrigo Sepúlveda',
        valorNuevo: 'Ana Valenzuela',
      },
      {
        id: 'hm-2',
        fecha: '10/12/2025 15:40',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Condición Comercial',
        detalle: 'Ampliación de plazo de pago de 15 a 30 días.',
        valorAnterior: '15 días',
        valorNuevo: '30 días',
      },
    ],
    kpis: {
      proformasTotales: 12,
      proformasAprobadas: 9,
      proformasRechazadas: 2,
      tasaAprobacion: 75.0,
      promedioVersiones: 1.3,
      cantidadReprocesos: 3,
      tiempoPromedioAprobacionDias: 2.2,
    },
  },
  {
    id: 'cli-2',
    rut: '81.201.000-K',
    razonSocial: 'Cencosud Retail S.A.',
    nombreFantasia: 'Cencosud (Jumbo / Easy / Paris)',
    giro: 'Grandes Tiendas y Supermercados',
    contactoPrincipal: {
      nombre: 'Claudia Morales Pinto',
      email: 'claudia.morales@cencosud.cl',
      telefono: '+56 9 8112 3344',
      cargo: 'Subgerente de Logística Inbound',
    },
    cuentaCorriente: {
      id: 'CTA-8012',
      numero: '11-902-88124',
      banco: 'Banco de Chile',
      lineaCredito: 120000000,
      saldoDisponible: 95400000,
      alias: 'Cuenta Corporativa Jumbo',
    },
    cuentasCorrientes: [
      { id: 'CTA-8012', numero: '11-902-88124', banco: 'Banco de Chile', lineaCredito: 120000000, saldoDisponible: 95400000, alias: 'Cuenta Corporativa Jumbo' },
      { id: 'CTA-8013', numero: '12-902-88125', banco: 'Banco Estado', lineaCredito: 80000000, saldoDisponible: 64000000, alias: 'Cuenta Easy Logística' },
      { id: 'CTA-8014', numero: '77-902-88126', banco: 'Banco Scotiabank', lineaCredito: 90000000, saldoDisponible: 78200000, alias: 'Cuenta Paris Tiendas' },
      { id: 'CTA-8015', numero: '22-902-88127', banco: 'Banco BCI', lineaCredito: 60000000, saldoDisponible: 51000000, alias: 'Cuenta Santa Isabel' },
      { id: 'CTA-8016', numero: '33-902-88128', banco: 'Banco Security', lineaCredito: 50000000, saldoDisponible: 42300000, alias: 'Cuenta Mayorista Central' },
    ],
    ejecutivoId: 'exe-2',
    ejecutivoNombre: 'Rodrigo Sepúlveda',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-2',
      tipo: 'Acuerdo marco corporativo',
      descuentoAcordado: '14% en fletes nacionales consolidados',
      plazoPagoDias: 45,
      validezHasta: '30/06/2027',
      observaciones: 'Facturación quincenal con corte automático los días 15 y 30.',
    },
    proformasIds: ['PF-2025-0138'],
    historialModificaciones: [
      {
        id: 'hm-3',
        fecha: '02/03/2026 09:15',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Condición Comercial',
        detalle: 'Ajuste de descuento marco de 12% a 14% por volumen anual garantizado.',
        valorAnterior: '12%',
        valorNuevo: '14%',
      },
    ],
    kpis: {
      proformasTotales: 24,
      proformasAprobadas: 22,
      proformasRechazadas: 1,
      tasaAprobacion: 91.6,
      promedioVersiones: 1.1,
      cantidadReprocesos: 2,
      tiempoPromedioAprobacionDias: 1.5,
    },
  },
  {
    id: 'cli-3',
    rut: '96.543.210-9',
    razonSocial: 'Distribuidora Sur S.A.',
    nombreFantasia: 'Distribuidora del Sur',
    giro: 'Distribución Mayorista de Alimentos y Bebidas',
    contactoPrincipal: {
      nombre: 'Manuel Figueroa Lagos',
      email: 'mfigueroa@distribuidorasur.cl',
      telefono: '+56 9 7654 3210',
      cargo: 'Jefe de Operaciones Logísticas',
    },
    cuentaCorriente: {
      id: 'CTA-8801',
      numero: '55-321-99801',
      banco: 'Banco Santander',
      lineaCredito: 35000000,
      saldoDisponible: 19800000,
      alias: 'Cuenta Principal',
    },
    cuentasCorrientes: [
      { id: 'CTA-8801', numero: '55-321-99801', banco: 'Banco Santander', lineaCredito: 35000000, saldoDisponible: 19800000, alias: 'Cuenta Principal' },
      { id: 'CTA-8802', numero: '00-321-99802', banco: 'Banco de Chile', lineaCredito: 20000000, saldoDisponible: 14500000, alias: 'Cuenta Secundaria' },
    ],
    ejecutivoId: 'exe-3',
    ejecutivoNombre: 'Marcela Soto',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-3',
      tipo: 'Tarifa especial por ruta sur',
      descuentoAcordado: '12% en pallets / 10% paquetería B2B',
      plazoPagoDias: 30,
      validezHasta: '31/12/2026',
      observaciones: 'Sujeto a verificación mensual de cubicaje.',
    },
    proformasIds: ['PF-2025-0141'],
    historialModificaciones: [
      {
        id: 'hm-4',
        fecha: '18/06/2026 16:20',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Asignación Ejecutivo',
        detalle: 'Asignación a Marcela Soto tras redistribución de zona sur.',
        valorAnterior: 'Felipe Morales',
        valorNuevo: 'Marcela Soto',
      },
    ],
    kpis: {
      proformasTotales: 15,
      proformasAprobadas: 11,
      proformasRechazadas: 3,
      tasaAprobacion: 73.3,
      promedioVersiones: 1.5,
      cantidadReprocesos: 5,
      tiempoPromedioAprobacionDias: 2.9,
    },
  },
  {
    id: 'cli-4',
    rut: '78.456.789-1',
    razonSocial: 'MegaStore Chile S.A.C.',
    nombreFantasia: 'MegaStore',
    giro: 'Comercio Minorista y Línea Blanca',
    contactoPrincipal: {
      nombre: 'Ignacio Valenzuela Toro',
      email: 'ivalenzuela@megastore.cl',
      telefono: '+56 9 6543 2199',
      cargo: 'Gerente de Cadena de Suministro',
    },
    cuentaCorriente: {
      id: 'CTA-3011',
      numero: '22-881-30119',
      banco: 'Banco BCI',
      lineaCredito: 25000000,
      saldoDisponible: 8400000,
      alias: 'Cuenta Única Línea Blanca',
    },
    cuentasCorrientes: [
      { id: 'CTA-3011', numero: '22-881-30119', banco: 'Banco BCI', lineaCredito: 25000000, saldoDisponible: 8400000, alias: 'Cuenta Única Línea Blanca' },
    ],
    ejecutivoId: 'exe-4',
    ejecutivoNombre: 'Felipe Morales',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-4',
      tipo: 'Tarifa especial regional',
      descuentoAcordado: '8% estándar',
      plazoPagoDias: 15,
      validezHasta: '31/10/2026',
      observaciones: 'Cliente crítico por rechazos reiterados de cubicaje.',
    },
    proformasIds: ['PF-2025-0140'],
    historialModificaciones: [
      {
        id: 'hm-5',
        fecha: '20/07/2025 18:35',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Estado',
        detalle: 'Derivación de cuenta a seguimiento prioritario KAM por 3 rechazos consecutivos en PF-2025-0140.',
      },
    ],
    kpis: {
      proformasTotales: 14,
      proformasAprobadas: 7,
      proformasRechazadas: 6,
      tasaAprobacion: 50.0,
      promedioVersiones: 1.9,
      cantidadReprocesos: 8,
      tiempoPromedioAprobacionDias: 4.1,
    },
  },
  {
    id: 'cli-5',
    rut: '77.123.456-8',
    razonSocial: 'Falabella Retail S.A.',
    nombreFantasia: 'Falabella',
    giro: 'Retail Integral y Comercio Electrónico',
    contactoPrincipal: {
      nombre: 'Javiera Vergara Lira',
      email: 'jvergara@falabella.cl',
      telefono: '+56 9 9234 5678',
      cargo: 'Jefa de Liquidación de Transportes',
    },
    cuentaCorriente: {
      id: 'CTA-5541',
      numero: '99-443-55410',
      banco: 'Banco Falabella',
      lineaCredito: 150000000,
      saldoDisponible: 112000000,
      alias: 'Cuenta Banco Falabella Retail',
    },
    cuentasCorrientes: [
      { id: 'CTA-5541', numero: '99-443-55410', banco: 'Banco Falabella', lineaCredito: 150000000, saldoDisponible: 112000000, alias: 'Cuenta Banco Falabella Retail' },
      { id: 'CTA-5542', numero: '00-443-55411', banco: 'Banco de Chile', lineaCredito: 100000000, saldoDisponible: 84000000, alias: 'Cuenta eCommerce Sodimac' },
      { id: 'CTA-5543', numero: '55-443-55412', banco: 'Banco Santander', lineaCredito: 70000000, saldoDisponible: 59000000, alias: 'Cuenta Tottus Logística' },
      { id: 'CTA-5544', numero: '22-443-55413', banco: 'Banco BCI', lineaCredito: 50000000, saldoDisponible: 41500000, alias: 'Cuenta Mallplaza' },
    ],
    ejecutivoId: 'exe-1',
    ejecutivoNombre: 'Ana Valenzuela',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-5',
      tipo: 'Tarifa preferencial eCommerce',
      descuentoAcordado: '15% RM / 12% Regiones',
      plazoPagoDias: 30,
      validezHasta: '31/12/2026',
      observaciones: 'Factor volumétrico especial 1:180 para paquetería express.',
    },
    proformasIds: ['PF-2026-0208'],
    historialModificaciones: [
      {
        id: 'hm-6',
        fecha: '05/01/2026 10:00',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Asignación Ejecutivo',
        detalle: 'Asignación prioritaria a Ana Valenzuela por manejo de cuentas estratégicas.',
        valorNuevo: 'Ana Valenzuela',
      },
    ],
    kpis: {
      proformasTotales: 18,
      proformasAprobadas: 15,
      proformasRechazadas: 2,
      tasaAprobacion: 83.3,
      promedioVersiones: 1.2,
      cantidadReprocesos: 3,
      tiempoPromedioAprobacionDias: 1.8,
    },
  },
  {
    id: 'cli-6',
    rut: '76.123.456-7',
    razonSocial: 'Logística Pacífico S.A.',
    nombreFantasia: 'Logística Pacífico',
    giro: 'Transporte Marítimo y Terrestre',
    contactoPrincipal: {
      nombre: 'Héctor Carrillo V.',
      email: 'hcarrillo@logpaci.cl',
      telefono: '+56 9 8765 1209',
      cargo: 'Gerente de Operaciones',
    },
    cuentaCorriente: {
      id: 'CTA-9021',
      numero: '44-902-11883',
      banco: 'Banco Itaú',
      lineaCredito: 40000000,
      saldoDisponible: 34100000,
      alias: 'Cuenta Marítima Valparaíso',
    },
    cuentasCorrientes: [
      { id: 'CTA-9021', numero: '44-902-11883', banco: 'Banco Itaú', lineaCredito: 40000000, saldoDisponible: 34100000, alias: 'Cuenta Marítima Valparaíso' },
      { id: 'CTA-9022', numero: '77-902-11884', banco: 'Banco Scotiabank', lineaCredito: 35000000, saldoDisponible: 28000000, alias: 'Cuenta Terrestre San Antonio' },
      { id: 'CTA-9023', numero: '00-902-11885', banco: 'Banco de Chile', lineaCredito: 30000000, saldoDisponible: 25400000, alias: 'Cuenta Carga Norte' },
      { id: 'CTA-9024', numero: '22-902-11886', banco: 'Banco BCI', lineaCredito: 25000000, saldoDisponible: 19000000, alias: 'Cuenta Puerto Montt' },
      { id: 'CTA-9025', numero: '12-902-11887', banco: 'Banco Estado', lineaCredito: 20000000, saldoDisponible: 18200000, alias: 'Cuenta Aduanas' },
      { id: 'CTA-9026', numero: '55-902-11888', banco: 'Banco Santander', lineaCredito: 30000000, saldoDisponible: 24000000, alias: 'Cuenta Operaciones Santiago' },
    ],
    ejecutivoId: 'exe-3',
    ejecutivoNombre: 'Marcela Soto',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-6',
      tipo: 'Tarifa diferenciada',
      descuentoAcordado: '9% global',
      plazoPagoDias: 30,
      validezHasta: '30/11/2026',
      observaciones: 'Condición vigente sin observaciones.',
    },
    proformasIds: ['PF-2025-0143'],
    historialModificaciones: [],
    kpis: {
      proformasTotales: 10,
      proformasAprobadas: 9,
      proformasRechazadas: 0,
      tasaAprobacion: 90.0,
      promedioVersiones: 1.0,
      cantidadReprocesos: 0,
      tiempoPromedioAprobacionDias: 1.2,
    },
  },
  {
    id: 'cli-7',
    rut: '77.890.123-4',
    razonSocial: 'Trans-Andes Cargo Ltda.',
    nombreFantasia: 'Trans-Andes Cargo',
    giro: 'Transporte de Carga y Encomiendas',
    contactoPrincipal: {
      nombre: 'Patricia Albornoz R.',
      email: 'palbornoz@transandescargo.cl',
      telefono: '+56 9 5543 9021',
      cargo: 'Jefa de Contabilidad',
    },
    cuentaCorriente: {
      id: 'CTA-4410',
      numero: '77-441-00921',
      banco: 'Banco Scotiabank',
      lineaCredito: 20000000,
      saldoDisponible: 16500000,
      alias: 'Cuenta Principal Carga',
    },
    cuentasCorrientes: [
      { id: 'CTA-4410', numero: '77-441-00921', banco: 'Banco Scotiabank', lineaCredito: 20000000, saldoDisponible: 16500000, alias: 'Cuenta Principal Carga' },
    ],
    ejecutivoId: 'exe-2',
    ejecutivoNombre: 'Rodrigo Sepúlveda',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-7',
      tipo: 'Descuento volumétrico',
      descuentoAcordado: '7% sobre 200 envíos',
      plazoPagoDias: 15,
      validezHasta: '31/12/2026',
      observaciones: 'Pago mediante transferencia bancaria automática.',
    },
    proformasIds: ['PF-2025-0142'],
    historialModificaciones: [],
    kpis: {
      proformasTotales: 8,
      proformasAprobadas: 7,
      proformasRechazadas: 1,
      tasaAprobacion: 87.5,
      promedioVersiones: 1.1,
      cantidadReprocesos: 1,
      tiempoPromedioAprobacionDias: 1.6,
    },
  },
  {
    id: 'cli-8',
    rut: '79.111.222-3',
    razonSocial: 'Importadora Bello Ltda.',
    nombreFantasia: 'Importadora Bello',
    giro: 'Importación y Comercialización de Artículos de Hogar',
    contactoPrincipal: {
      nombre: 'Felipe Bello Zúñiga',
      email: 'fbello@importadorabello.cl',
      telefono: '+56 9 4432 1199',
      cargo: 'Director Comercial',
    },
    cuentaCorriente: {
      id: 'CTA-1002',
      numero: '12-100-22991',
      banco: 'Banco Estado',
      lineaCredito: 15000000,
      saldoDisponible: 12100000,
      alias: 'Cuenta Principal Importadora',
    },
    cuentasCorrientes: [
      { id: 'CTA-1002', numero: '12-100-22991', banco: 'Banco Estado', lineaCredito: 15000000, saldoDisponible: 12100000, alias: 'Cuenta Principal Importadora' },
      { id: 'CTA-1003', numero: '00-100-22992', banco: 'Banco de Chile', lineaCredito: 10000000, saldoDisponible: 8400000, alias: 'Cuenta Sucursal Iquique Zofri' },
      { id: 'CTA-1004', numero: '22-100-22993', banco: 'Banco BCI', lineaCredito: 12000000, saldoDisponible: 9800000, alias: 'Cuenta Casa Matriz' },
    ],
    ejecutivoId: 'exe-4',
    ejecutivoNombre: 'Felipe Morales',
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-8',
      tipo: 'Tarifa diferenciada',
      descuentoAcordado: '5% base',
      plazoPagoDias: 15,
      validezHasta: '31/12/2026',
      observaciones: 'Cliente en evaluación de aumento de cupo comercial.',
    },
    proformasIds: ['PF-2025-0139'],
    historialModificaciones: [],
    kpis: {
      proformasTotales: 6,
      proformasAprobadas: 5,
      proformasRechazadas: 1,
      tasaAprobacion: 83.3,
      promedioVersiones: 1.2,
      cantidadReprocesos: 1,
      tiempoPromedioAprobacionDias: 2.0,
    },
  },

  // ------------------------------------------------------------------------
  // CLIENTES SIN EJECUTIVO ASIGNADO (SIN ASIGNAR - REQUERIMIENTO JIRA)
  // ------------------------------------------------------------------------
  {
    id: 'cli-9',
    rut: '76.998.776-5',
    razonSocial: 'Alimentos del Sur SpA',
    nombreFantasia: 'Alisur',
    giro: 'Producción y Distribución de Alimentos',
    contactoPrincipal: {
      nombre: 'Verónica Cárdenas Mora',
      email: 'vcardenas@alisur.cl',
      telefono: '+56 9 7788 9911',
      cargo: 'Jefa de Adquisiciones',
    },
    cuentaCorriente: {
      id: 'CTA-9901',
      numero: '33-990-11244',
      banco: 'Banco BCI',
      lineaCredito: 30000000,
      saldoDisponible: 30000000,
      alias: 'Cuenta Primaria B2B',
    },
    cuentasCorrientes: [
      { id: 'CTA-9901', numero: '33-990-11244', banco: 'Banco BCI', lineaCredito: 30000000, saldoDisponible: 30000000, alias: 'Cuenta Primaria B2B' },
      { id: 'CTA-9902', numero: '55-990-11245', banco: 'Banco Santander', lineaCredito: 25000000, saldoDisponible: 25000000, alias: 'Cuenta Lácteos y Refrigerados' },
    ],
    ejecutivoId: undefined, // Sin ejecutivo asignado
    ejecutivoNombre: undefined,
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-9',
      tipo: 'Tarifa estándar B2B',
      descuentoAcordado: 'Sin convenio activo',
      plazoPagoDias: 15,
      validezHasta: '31/12/2026',
      observaciones: 'Cliente nuevo ingresado por plataforma comercial. Pendiente asignación de ejecutivo.',
    },
    proformasIds: [],
    historialModificaciones: [
      {
        id: 'hm-7',
        fecha: '16/09/2026 14:10',
        usuario: 'Sistema Automático',
        tipoModificacion: 'Datos Empresa',
        detalle: 'Alta de cliente en plataforma Starken Facturación Especial.',
      },
    ],
    kpis: {
      proformasTotales: 0,
      proformasAprobadas: 0,
      proformasRechazadas: 0,
      tasaAprobacion: 0,
      promedioVersiones: 0,
      cantidadReprocesos: 0,
      tiempoPromedioAprobacionDias: 0,
    },
  },
  {
    id: 'cli-10',
    rut: '79.888.111-2',
    razonSocial: 'Constructora Metropolitana S.A.',
    nombreFantasia: 'Constructora Metro',
    giro: 'Edificación y Obras Civiles',
    contactoPrincipal: {
      nombre: 'Rodrigo Baeza Tapia',
      email: 'rbaeza@metrosa.cl',
      telefono: '+56 9 3322 1100',
      cargo: 'Gerente de Administración',
    },
    cuentaCorriente: {
      id: 'CTA-7732',
      numero: '55-773-22001',
      banco: 'Banco Santander',
      lineaCredito: 18000000,
      saldoDisponible: 18000000,
      alias: 'Cuenta Santander Matriz',
    },
    cuentasCorrientes: [
      { id: 'CTA-7732', numero: '55-773-22001', banco: 'Banco Santander', lineaCredito: 18000000, saldoDisponible: 18000000, alias: 'Cuenta Santander Matriz' },
      { id: 'CTA-7733', numero: '00-773-22002', banco: 'Banco de Chile', lineaCredito: 15000000, saldoDisponible: 15000000, alias: 'Cuenta Obra Las Condes' },
      { id: 'CTA-7734', numero: '22-773-22003', banco: 'Banco BCI', lineaCredito: 12000000, saldoDisponible: 12000000, alias: 'Cuenta Obra La Florida' },
      { id: 'CTA-7735', numero: '33-773-22004', banco: 'Banco Security', lineaCredito: 10000000, saldoDisponible: 10000000, alias: 'Cuenta Faenas Rancagua' },
      { id: 'CTA-7736', numero: '88-773-22005', banco: 'Banco BICE', lineaCredito: 14000000, saldoDisponible: 14000000, alias: 'Cuenta Proveedores Prefabricados' },
      { id: 'CTA-7737', numero: '77-773-22006', banco: 'Banco Scotiabank', lineaCredito: 8000000, saldoDisponible: 8000000, alias: 'Cuenta Maquinarias' },
      { id: 'CTA-7738', numero: '44-773-22007', banco: 'Banco Itaú', lineaCredito: 10000000, saldoDisponible: 10000000, alias: 'Cuenta Insumos Menores' },
    ],
    ejecutivoId: undefined, // Sin ejecutivo asignado
    ejecutivoNombre: undefined,
    estado: 'Inactivo',
    condicionesComerciales: {
      id: 'cond-10',
      tipo: 'Tarifa general',
      descuentoAcordado: '0%',
      plazoPagoDias: 30,
      validezHasta: '30/09/2025',
      observaciones: 'Cuenta temporalmente suspendida por inactividad comercial.',
    },
    proformasIds: [],
    historialModificaciones: [
      {
        id: 'hm-8',
        fecha: '01/08/2025 10:00',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Estado',
        detalle: 'Cambio de estado a Inactivo por falta de movimientos en 12 meses.',
        valorAnterior: 'Activo',
        valorNuevo: 'Inactivo',
      },
    ],
    kpis: {
      proformasTotales: 3,
      proformasAprobadas: 2,
      proformasRechazadas: 1,
      tasaAprobacion: 66.7,
      promedioVersiones: 1.3,
      cantidadReprocesos: 1,
      tiempoPromedioAprobacionDias: 3.0,
    },
  },
  {
    id: 'cli-11',
    rut: '77.555.444-3',
    razonSocial: 'Farmacias Cruz del Mar SpA',
    nombreFantasia: 'Cruz del Mar',
    giro: 'Distribución Farmacéutica e Insumos Médicos',
    contactoPrincipal: {
      nombre: 'Loreto Sanhueza Peña',
      email: 'lsanhueza@cruzdelmar.cl',
      telefono: '+56 9 6677 8899',
      cargo: 'Supervisora de Despachos',
    },
    cuentaCorriente: {
      id: 'CTA-4419',
      numero: '12-441-99882',
      banco: 'Banco de Chile',
      lineaCredito: 45000000,
      saldoDisponible: 45000000,
      alias: 'Cuenta Principal Farmacéutica',
    },
    cuentasCorrientes: [
      { id: 'CTA-4419', numero: '12-441-99882', banco: 'Banco de Chile', lineaCredito: 45000000, saldoDisponible: 45000000, alias: 'Cuenta Principal Farmacéutica' },
      { id: 'CTA-4420', numero: '12-441-99883', banco: 'Banco Estado', lineaCredito: 30000000, saldoDisponible: 30000000, alias: 'Cuenta Convenio Cenabast' },
      { id: 'CTA-4421', numero: '55-441-99884', banco: 'Banco Santander', lineaCredito: 35000000, saldoDisponible: 35000000, alias: 'Cuenta Cadena Regional Norte' },
      { id: 'CTA-4422', numero: '22-441-99885', banco: 'Banco BCI', lineaCredito: 28000000, saldoDisponible: 28000000, alias: 'Cuenta Cadena Regional Sur' },
      { id: 'CTA-4423', numero: '44-441-99886', banco: 'Banco Itaú', lineaCredito: 20000000, saldoDisponible: 20000000, alias: 'Cuenta Vacunas y Biológicos' },
      { id: 'CTA-4424', numero: '77-441-99887', banco: 'Banco Scotiabank', lineaCredito: 22000000, saldoDisponible: 22000000, alias: 'Cuenta Insumos Clínicos' },
      { id: 'CTA-4425', numero: '88-441-99888', banco: 'Banco BICE', lineaCredito: 18000000, saldoDisponible: 18000000, alias: 'Cuenta Equipamiento Médico' },
      { id: 'CTA-4426', numero: '33-441-99889', banco: 'Banco Security', lineaCredito: 15000000, saldoDisponible: 15000000, alias: 'Cuenta Despacho Hospitalario' },
      { id: 'CTA-4427', numero: '99-441-99890', banco: 'Banco Falabella', lineaCredito: 12000000, saldoDisponible: 12000000, alias: 'Cuenta Farmacias Asociadas' },
    ],
    ejecutivoId: undefined, // Sin ejecutivo asignado
    ejecutivoNombre: undefined,
    estado: 'Activo',
    condicionesComerciales: {
      id: 'cond-11',
      tipo: 'Tarifa transporte temperatura controlada',
      descuentoAcordado: '11% en envíos refrigerados',
      plazoPagoDias: 30,
      validezHasta: '31/12/2026',
      observaciones: 'Cuenta transferida desde filial regional. Requiere asignación de ejecutivo especialista.',
    },
    proformasIds: [],
    historialModificaciones: [
      {
        id: 'hm-9',
        fecha: '17/09/2026 08:30',
        usuario: 'Carlos Muñoz',
        tipoModificacion: 'Datos Empresa',
        detalle: 'Aprobación de cuenta corriente comercial. Lista para asignación.',
      },
    ],
    kpis: {
      proformasTotales: 0,
      proformasAprobadas: 0,
      proformasRechazadas: 0,
      tasaAprobacion: 0,
      promedioVersiones: 0,
      cantidadReprocesos: 0,
      tiempoPromedioAprobacionDias: 0,
    },
  },
];

export const MOCK_AUDIT: AuditLog[] = [
  {
    id: 'a1',
    ts: '17/09/2026 10:45:12',
    fechaHora: '17/09/2026 10:45:12',
    usuario: 'Carlos Muñoz',
    rol: 'Jefatura',
    accion: 'Aprobación',
    recurso: 'PF-2025-0141',
    objetoAfectado: 'Proforma v2 (Distribuidora Sur S.A.)',
    estadoAnterior: 'Pendiente_Autorizacion',
    estadoNuevo: 'Autorizada (V°B° Jefatura)',
    version: 'v2',
    motivoObservaciones: 'V°B° concedido tras validación de ajuste de descuento según contrato anexo 2025.',
    ip: '10.0.2.12',
  },
  {
    id: 'a2',
    ts: '17/09/2026 09:20:05',
    fechaHora: '17/09/2026 09:20:05',
    usuario: 'Carlos Muñoz',
    rol: 'Jefatura',
    accion: 'Reasignación de Ejecutivo',
    recurso: 'cli-1',
    objetoAfectado: 'Retail Logistics Chile S.A.',
    estadoAnterior: 'Ejecutivo: Rodrigo Sepúlveda',
    estadoNuevo: 'Ejecutivo: Ana Valenzuela',
    motivoObservaciones: 'Balanceo de carga de cartera por inicio de temporada alta.',
    ip: '10.0.2.12',
  },
  {
    id: 'a3',
    ts: '16/09/2026 16:30:40',
    fechaHora: '16/09/2026 16:30:40',
    usuario: 'Ana Valenzuela',
    rol: 'Ejecutivo',
    accion: 'Creación Nueva Versión',
    recurso: 'PF-2026-0208',
    objetoAfectado: 'Proforma Falabella Retail S.A.',
    estadoAnterior: 'Rechazada v1',
    estadoNuevo: 'Pendiente de validación (v2)',
    version: 'v2',
    motivoObservaciones: 'Recálculo con factor volumétrico estándar 1:180 tras objeción del cliente.',
    ip: '10.0.1.45',
  },
  {
    id: 'a4',
    ts: '16/09/2026 14:15:22',
    fechaHora: '16/09/2026 14:15:22',
    usuario: 'Carlos Muñoz',
    rol: 'Jefatura',
    accion: 'Rechazo',
    recurso: 'PF-2025-0140',
    objetoAfectado: 'MegaStore Chile S.A.C.',
    estadoAnterior: 'Pendiente_Autorizacion',
    estadoNuevo: 'Derivada a KAM',
    version: 'v3',
    motivoObservaciones: 'Acumula 3 discrepancias consecutivas en cubicaje; se deriva a negociación comercial KAM.',
    ip: '10.0.2.12',
  },
  {
    id: 'a5',
    ts: '15/09/2026 11:10:00',
    fechaHora: '15/09/2026 11:10:00',
    usuario: 'Marcela Soto',
    rol: 'Ejecutivo',
    accion: 'Envío Proforma',
    recurso: 'PF-2025-0143',
    objetoAfectado: 'Logística Pacífico S.A.',
    estadoAnterior: 'Borrador',
    estadoNuevo: 'Enviada_Cliente',
    version: 'v1',
    motivoObservaciones: 'Envío formal de proforma quincenal.',
    ip: '10.0.1.52',
  },
  {
    id: 'a6',
    ts: '14/09/2026 17:05:18',
    fechaHora: '14/09/2026 17:05:18',
    usuario: 'Carlos Muñoz',
    rol: 'Jefatura',
    accion: 'Cambio Condiciones Comerciales',
    recurso: 'cli-2',
    objetoAfectado: 'Cencosud Retail S.A.',
    estadoAnterior: 'Descuento 12% / Plazo 30 días',
    estadoNuevo: 'Descuento 14% / Plazo 45 días',
    motivoObservaciones: 'Firma de anexo corporativo nacional 2026-2027.',
    ip: '10.0.2.12',
  },
  {
    id: 'a7',
    ts: '14/09/2026 09:00:11',
    fechaHora: '14/09/2026 09:00:11',
    usuario: 'Rodrigo Sepúlveda',
    rol: 'Ejecutivo',
    accion: 'Facturación',
    recurso: 'PF-2025-0138',
    objetoAfectado: 'Cencosud Retail S.A.',
    estadoAnterior: 'Aprobada_Cliente',
    estadoNuevo: 'Facturado (FAC-890214)',
    version: 'v1',
    motivoObservaciones: 'Factura emitida y registrada en SAP con respaldo PDF adjunto.',
    ip: '10.0.1.48',
  },
];

